### ISSUE TITLE
 no attribute 'use_translation

### ISSUE THREAD

**Issue by ekswathi** [oormicreations/VSEIndic#2]
win 10
Attribute Error: 'imageSequence' object has no attribute 'use_translation'
![issue](https://user-images.githubusercontent.com/51689618/101589589-bf65b900-3a0e-11eb-8178-2dbe1cdfa2bc.JPG)

**Comment by ekswathi** [comment]
![issue](https://user-images.githubusercontent.com/51689618/101589736-094e9f00-3a0f-11eb-9586-7bddb1f46410.JPG)

**Comment by oormicreations** [comment]
Please mention your blender version.
Please see the readme for supported versions.

**Comment by ekswathi** [comment]
I tried blender2.82, 2.91 and blender 2.92.  I tried with the sanakrit2003 font. But no result

**Comment by ekswathi** [comment]
It is showing the menu in vse.  but when I try to press the create indic text button it give only empty png strips

**Comment by oormicreations** [comment]
This plugin requires pyvips and libvips. Please see the readme for installation instructions on linux. If you are on windows, you will need to search for exact installation process.

**Comment by ekswathi** [comment]
I installed pyvips and libvips. and i am able to enable the addon.  But it give only empty png strips. No text.

**Comment by oormicreations** [comment]
Are there any error messages? Please check the console also.
Please let me know how the pyvips and libvips was done.

**Comment by ekswathi** [comment]
I followed this tutorial to install  both libraries 
https://www.youtube.com/watch?v=O5iBsdAd1_w

**Comment by oormicreations** [comment]
Please type these commands in blender python console (as shown in the attached image) , and let me know the result of these commands.

```
>>>import pyvips
>>>image = pyvips.Image.text("test", width=100)

```
![Screenshot from 2020-12-13 22-52-28](https://user-images.githubusercontent.com/11452251/102018879-10223c80-3d96-11eb-8cb0-5c10961d8cac.png)

**Comment by ekswathi** [comment]
No special messages as you can see in the attached screenshot.  Thank you for finding time for solving the issue.

![Capture](https://user-images.githubusercontent.com/51689618/102034499-222acc00-3de4-11eb-80e4-bcfc494ca2a2.JPG)

**Comment by ekswathi** [comment]
![Capture1](https://user-images.githubusercontent.com/51689618/102040983-4393b400-3df4-11eb-8854-61d6384158f7.JPG)

**Comment by oormicreations** [comment]
Thank you for your patience. I cannot check it in windows, but I tried upgrading my libvips to latest version to recreate the error.
It looks like on windows it produces a multiband image, not a b-w image, the size is also different.
Can you send me the png image. It will be in a folder called vseindic where the blend file was saved. To generate the image, leave everything as default and just click the create button.

**Comment by ekswathi** [comment]
Oh my god.  I am really sorry to waste your time.  It is working properly.  I did a big mistake.  I didn't saved the file.  When I saved the file It is working like a charm.
Thank you for the lifesaver addon and sorry again for wasting your precious time.

**Comment by oormicreations** [comment]
Great. No problem. I will add a save check to ensure that users save the file.
